name: Test

on:
  pull_request:

jobs:
  ruby-sdk-test:
    runs-on: ubuntu-latest
    env:
      COVERAGE: true
    strategy:
      matrix:
        ruby-version:
          - '2.6'
          - '2.7'
          - '3.0'
          - '3.1'
          - '3.2'
          - '3.3'
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
      - name: Install dependencies
        run: |
          bundle config set --local without 'rubocop'
          bundle install
      - name: Run tests
        run: rake spec
      - name: Report coverage
        if: ${{ matrix.ruby-version }} == '3.3'
        uses: romeovs/lcov-reporter-action@v0.3.1
        with:
          lcov-file: ./coverage/lcov/hackle-ruby-sdk.lcov
          github-token: ${{ secrets.GITHUB_TOKEN }}
