name: Test

on:
  pull_request:

jobs:
  ruby-sdk-test:
    runs-on: ubuntu-latest
    env:
      COVERAGE: true
    strategy:
      matrix:
        ruby-version:
          - 2.6.0
          - 2.7.0
          - 3.0.0
          - 3.1.0
          - 3.2.0
          - 3.3.0
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
      - name: Install dependencies
        run: |
          bundle config set --local without 'rubocop'
          bundle install
      - name: Run tests
        run: rake spec
      - name: Coverage
        uses: irongut/CodeCoverageSummary@v1.3.0
        if: ${{ matrix.ruby-version }} == 3.3.0
        with:
          filename: coverage/coverage.xml
          badge: true
          fail_below_min: true
          format: markdown
          hide_branch_rate: true
          hide_complexity: true
          indicators: true
          output: both
          thresholds: '80 90'
      - name: Report Coverage
        uses: marocchino/sticky-pull-request-comment@v2
        if: ${{ matrix.ruby-version }} == 3.3.0
        with:
          recreate: true
          path: code-coverage-results.md
