name: Test

on:
  pull_request:

jobs:
  ruby-sdk-test:
    runs-on: ubuntu-latest
    env:
      COVERAGE: true
    strategy:
      matrix:
        ruby-version:
          - '2.6'
          - '3.2'
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler: 2.4.22
      - name: Install dependencies
        run: |
          bundle config set --local without 'rubocop'
          bundle install
      - name: Run tests
        run: rake test
